---
version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:12'
    steps:
      - checkout
      - run:
          name: install
          command: 'npm i'
      - run:
          name: build
          command: 'npm run build'
      - run:
          name: test
          command: 'npm run test:ci'
      - run:
          name: release
          command: 'npm run semantic-release || true'
workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: gh-npm-public
